#指定mybatis映射文件的地址
mybatis:
  mapper-locations: classpath:mappers/*.xml

#配置数据源
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/webchat?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 88888888
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /

  redis:
    host: 127.0.0.1
    port: 6379
    # 默认空
    password:
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        #连接池中最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0


#邮箱配置
email:
  #发送方
  sender: qzh1720505246@163.com
  #密码
  password: CHDBMSVMNYNPIJGA
  #邮箱host
  host: smtp.163.com

#验证码的配置
validation:
  code:
    #长度
    length: 6
