#指定mybatis映射文件的地址
mybatis:
  mapper-locations: classpath:mappers/*.xml

#配置数据源
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/webchat?useUnicode=true&characterEncoding=utf8
    username: root
    password: 88888888
    driver-class-name: com.mysql.jdbc.Driver

