#指定mybatis映射文件的地址
mybatis:
  mapper-locations: classpath:mappers/*.xml

#配置数据源
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/webchat?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 88888888
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
     host: 192.168.137.3
     port: 5672
     username: guest
     password: guest
     virtual-host: /

